### ISSUE TITLE
add library to npm

### ISSUE THREAD

**Issue by Kaliph** [evs-broadcast/node-emberplus#20]
Hello it would be nice if you could add this library to npm. So it could be installed online.
Otherwise it would be helpful to add an example how to install the library from a local file so it could be used like in the example. 

I was trying to use 

npm install ./node_modules/node-emberplus-master/ --save 

But it seems not the right way to do it. 

Thankyou for answering my noob question!

**Comment by dufourgilles** [comment]
Here is how it looks like in our package.json

"emberplus": "evs-broadcast/node-emberplus#1.7.15",

**Comment by Kaliph** [comment]
What I´ve meant is that you´re able to do something like this.

npm install node-emberplus --save

And the packages needed get automatically downloaded from npm.
Also the package with it´s current version will be saved in package.json file in my project.

Hope this makes the request more clear. Thankyou

**Comment by Kaliph** [comment]
Thanks for answering my noob question. I think I´ve understood now how it works.
