### ISSUE TITLE
Add Example how to read Ember Tree and Switch Input of a Router e.g.

### ISSUE THREAD

**Issue by Kaliph** [evs-broadcast/node-emberplus#21]
Could you please add an example how to read the EmberTree from a device to see how many inputs and outputs a router has. After counting the inputs it would be nice to have an example on how to switch inputs to outputs. Thankyou very much

**Comment by Kaliph** [comment]
I am trying to connect to a TinyEmberPlusRouter and read all it´s values. with this piece of code 

`var root;
var tree = new DeviceTree("localhost", 9092);
tree.connect()
.then(() => { 

   return tree.getDirectory();
})
.then((r) => { 
   root = r ;
   return tree.expand(r.elements[0]);
})
.then((data) => {

   console.log(tree);

})
.catch((err) => {

});`

I would like to read the tree from a device and convert it into xml or json format. How could this be achieved? After I have all the values, I would like to start to change values. I couldn´t find any examples on how to do this. Thankyou

**Comment by dufourgilles** [comment]
Assuming you are successfully connected.

> **tree.getDirectory();**
Promise { <pending> }
> tree.root
Root {
  elements: [ QualifiedNode { path: '1', contents: [Object] } ] }
> tree.root.elements[0]
QualifiedNode {
  path: '1',
  contents: NodeContents { isOnline: true, identifier: 'router' } }
> **tree.expand(tree.root.elements[0])**
Promise { <pending> }
> tree.root.elements[0]
QualifiedNode {
  path: '1',
  contents: NodeContents { isOnline: true, identifier: 'router' },
  children: 
   [ QualifiedNode { path: '1.0', contents: [Object], children: [Object] },
     QualifiedNode { path: '1.1', contents: [Object], children: [Object] },
     QualifiedNode { path: '1.2', contents: [Object], children: [Object] },
     QualifiedNode { path: '1.3', contents: [Object], children: [Object] },
     QualifiedNode { path: '1.4', contents: [Object], children: [Object] } ] }
> tree.root.elements[0].children[3]
QualifiedNode {
  path: '1.3',
  contents: 
   NodeContents {
     isOnline: true,
     identifier: 'dynamic',
     description: 'Linear N:N with Dynamic Parameters' },
  children: 
   [ QualifiedNode { path: '1.3.1', contents: [Object], children: [Object] },
     QualifiedMatrix { path: '1.3.2', contents: [Object], connections: [Object] } ] }
> tree.root.elements[0].children[3].children[1]
QualifiedMatrix {
  path: '1.3.2',
  contents: 
   MatrixContents {
     type: { [Number: 2] key: 'nToN', value: 2, _options: [Object] },
     mode: { [Number: 0] key: 'linear', value: 0, _options: [Object] },
     identifier: 'matrix',
     targetCount: 2000,
     sourceCount: 2000,
     labels: [ [Object] ],
     parametersLocation: 0,
     gainParameterNumber: 1 },
  connections: 
   { '0': MatrixConnection { target: 0, sources: [Object] },
...

**Comment by Kaliph** [comment]
Ok thanks. I get the second promise correctly now. Could you share an example how to set a value, or connect input to output of a matrixswitch.

**Comment by Kaliph** [comment]
At the moment I am only using the Client/DeviceTree. What can be done with with the TreeServer? Do I have to use the Server to change a value on a device?  Wouldn´t the normal setup be that devices automatically connect to the Ember+ Server and register it´s deviceproperties using DNS-SD or M-DNS ?
Thanks for your help!

**Comment by dufourgilles** [comment]
You don’t need the server.
Unless you want to expose your own device via ember.

To change the value of a remote device via the ember-plus client, simply use the setValue function of the DeviceTree.

For example, if you have a tree that looks like this

root
 |——> node1
               |
               |— node 1.0
               |— node 1.1
                        |— parameter[0] = (integer) 17

You can do
parameter_0 = root.elements[0].children[1].children[0]
deviceTree.setValue(parameter_0, 34)


Gilles.

**Comment by Kaliph** [comment]
Ok thankyou. Is there also an automatic Ember+ Device detection?
Or is this something that is not addressed in the ember+ Protocol?

**Comment by dufourgilles** [comment]
Detection is not part of the protocol.
