### ISSUE TITLE
TreeServer.handleGetDirectory does not subscribe to child parameters

### ISSUE THREAD

**Issue by hkviseth** [evs-broadcast/node-emberplus#33]
Per the Ember+ specification, a getDirectory on a Node indicates

> that a consumer is interested in the entities below the node the command has been sent for.  That means, that parameters belonging to this node should report value changes to the consumer automatically.

Currently it seems TreeServer.handleGetDirectory() only creates a subscription for Matrix and Parameter elements when the getDirectory is called directly on the Matrix/Parameter, but not for child Matrix/Parameter elements when called on a Node.

Checking if element.getChildren() returns an array and then subscribing to all elements within the array seems to be a crude fix.

**Comment by dufourgilles** [comment]
I have added a fix in 1.7.23
