### ISSUE TITLE
Please add information how to install via npm to Readme.md

### ISSUE THREAD

**Issue by Kaliph** [evs-broadcast/node-emberplus#38]
Hello,
I am trying to install this library via npm.
when doing 'npm install emberplus --save'
If this line is correct It would be great if you would add this to Readme.md

After that I see that version 1.0.0 was installed.
Can you tell me what I am doing wrong? I want to get the latest version of emberplus.
I would like to get Version 1.7.23 e.g.

Thankyou

**Comment by VengefulVeggie** [comment]
> Hello,
> I am trying to install this library via npm.
> when doing 'npm install emberplus --save'
> If this line is correct It would be great if you would add this to Readme.md
> 
> After that I see that version 1.0.0 was installed.
> Can you tell me what I am doing wrong? I want to get the latest version of emberplus.
> I would like to get Version 1.7.23 e.g.
> 
> Thankyou

Hey Kaliph, 

If you look at NPM this repo only has version 1.0.0 hosted there.

Not to force you away from this repo but try https://github.com/dufourgilles/node-emberplus. It’s a newer fork of this and Gilles has been very active with development recently, it’s up to version 2.5.6 on npm.

run ‘npm i node-emberplus —save’ ,

If you always want to get the latest version of a package with npm try @latest : ‘npm i node-emberplus@latest —save’

**Comment by Kaliph** [comment]
Thanks for pointing me to the right place. I will checkout the mentioned library.
