### ISSUE TITLE
Question about setValue responses

### ISSUE THREAD

**Issue by jesperstarkar** [evs-broadcast/node-emberplus#4]
`setValue()` times out for me and rejects its promise. setValue assigns `self.callback` which is meant to resolve the setValue-promise, and it's this callback that times out and rejects the promise.

Currently only òn('connected')`, `on('error')` and `on('emberTree')` can run self.callback. I don't see an update to emberTree coming back as I setValue, hence all promises time out.

I sniffed the packets, and it doesn't seem to come any response at all to the value update, even the value in fact gets updated on the device.

Do you know if the device is supposed sending any response to the update, and do we expect this to reuslt in a new emberTree. Any ideas why I don't get any responses?

**Comment by jesperstarkar** [comment]
I _do_ get a new emberTree if any values gets changed on the device directly.

**Comment by jesperstarkar** [comment]
It does in fact respons with a new tree, but only if a value is in fact updated to a new value.

**Comment by dufourgilles** [comment]
I never used the setValue.
But clearly looks buggy.
The Treeserver.setValue returns a new promise but we never call resolve or reject.
I personally use replaceElement.

Gilles.

**Comment by jesperstarkar** [comment]
Sorry, I was talking about Device.setValue(). Turns out it works. I'll have a look at implementing subribe() next.

**Comment by dufourgilles** [comment]
ok.  Then a response is mandatory

https://github.com/Lawo/ember-plus/blob/master/documentation/Ember%2B%20Documentation.pdf <https://github.com/Lawo/ember-plus/blob/master/documentation/Ember+%20Documentation.pdf>

**Comment by jesperstarkar** [comment]
Thanks a lot for your time and help. It's quite much to learn both the protocol and library at once.
