### ISSUE TITLE
# Error when target is arbitrary number, higher than index

### ISSUE THREAD

**Issue by hwellink** [evs-broadcast/node-emberplus#42]
This comparison, checking for valid matrix targets, throws an error when the Provider uses a non-sequential numbering sequence.

Assignees: 
Labels: 

https://github.com/dufourgilles/node-emberplus/blob/53646255b7e6d7bc68e975148af4a8d703cbcb86/EmberLib/Matrix.js#L367

**Comment by dufourgilles** [comment]
ACK.
Created a new issue.

https://github.com/dufourgilles/node-emberplus/issues/19 <https://github.com/dufourgilles/node-emberplus/issues/19>

A fix will come shortly.

Gilles.

**Comment by dufourgilles** [comment]
Fix in 2.5.11
